### ISSUE TITLE
Homework 1

### ISSUE THREAD

**Issue by ArtMan-8** [ArtMan-8/aws-nodejs#1]
# Homework 1
### PREREQUISITES
- [x] Install the latest LTS (Long Term Support) version of Node.js (https://nodejs.org/en/), by any available means (.exe, nvm, brew, etc.). 
- [x] Check in the console (terminal) that the Node.js installation was done properly by running the following commands node -v or node -version. 
- [x] Create a repo for your homework tasks. 
- [x] Provide your mentor with the link to the repo and add read access permissions. 
- [x] Create package.json by running the following commands npm init or npm init -y. 
- [x] Install globally or locally npm package nodemon (https://github.com/remy/nodemon) to dev dependency. 
- [x] Get ready to watch the lectures and do the homework tasks to study the basic principles and approaches of development server-side applications with Node.js. 
- [x] All tasks must be written with TypeScript

#### Evaluation criteria
- [x] Task 1.1 is fulfilled to the full extent. 
- [x] Task 1.2 is fulfilled to the full extent; the file is loaded fully into the RAM. 
- [x] Task 1.2 is fulfilled to the full extent; the file is not loaded fully in the RAM (pipeline method https://nodejs.org/api/stream.html#stream_stream_pipeline_streams_callback). 
- [x] All the tasks are fulfilled to the full extent.

<hr />

### Task 1.1 
Write a program which reads a string from the standard input stdin, reverses it and then writes it to the standard output stdout.
- [x] The program should be started from npm script via nodemon (i.e. npm run task1). 
- [x] The program should be running in a stand-by mode and should not be terminated after the 
first-string processing. 

For example:
```
12345 678
876 54321

test data
atad tset
```

<hr />

### Task 1.2
Write a program which should do the following: 
- [x] Read the content of csv file from ./csv directory. Example:

| Book                                                        | Author                   | Amount    | Price      | 
| ------------------------------------------ |:-------------------:|:-----------:| --------:|
| The Compound Effect                               | Darren Hardy         | 5              | 9.48       |
| The 7 Habits of Highly Effective People     | Stephen R. Covey   | 4               | 23.48    |
| The Miracle Morning                                | Hal Elrod                | 10            | 21.34     |
| Influence: The Psychology of Persuasion   | Robert B. Cialdini    | 4              | 12.99     |
| The ONE Thing                                         | Gary Keller             | 1              | 11.18     |

- [x] Use the csvtojson package (https://github.com/Keyang/node-csvtojson) to convert csv file to json object. 
- [x] Write the csv file content to a new txt file. Use the following format: 
```
{"book":"The Compound Effect","author":"Darren Hardy","price":9.48}
{"book":"The 7 Habits of Highly Effective People","author":"Stephen R. Covey","price":23.48}
{"book":"The Miracle Morning","author":"Hal Elrod","price":21.34}
{"book":"Influence: The Psychology of Persuasion","author":"Robert B. Cialdini","price":12.99}
{"book":"The ONE Thing","author":"Gary Keller","price":11.18}
```
- [x] ⭐️ Write file to two separate sources simultaneously: file and DB. You can emulate writing into DB with simple promisified function ⭐️ This addition only for those who participated in NGM Run before.
- [x] Do not load all the content of the csv file into RAM. Use stream instead (read/write file content line by line). 
- [x] In case of read/write errors, log them in the console. 
- [x] The program should be started via npm script using nodemon (i.e. npm run task2).
